### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by MikeiLL** [jacobwgillespie/dotfiles#10]
Hi, again, Jacob and community.

I'm looking for some clarity on the `functions` directory.

From the README, I expected running, `dot` to take me to the `~/dotfiles` directory, but it's returning:

```
zsh: command not found: dot
```

I imagine I'm missing a step.

**Comment by jacobwgillespie** [comment]
Not sure, these lines are what sets the function load path, which presumably would be picking up `dot`:

https://github.com/jacobwgillespie/dotfiles/blob/main/symlinks/.zshrc.symlink#L21
https://github.com/jacobwgillespie/dotfiles/blob/main/symlinks/.zshrc.symlink#L25

There aren't any other steps for me with a blank environment and running `./setup`, so if everything's linked and installed correctly, not sure what would cause it not to work.

**Comment by MikeiLL** [comment]
Perfect! I had been using my own .zshrc, so had to add some of your content to mine. Hadn't heard of [Starship](https://starship.rs/guide/) before. Installed it. Thank you!
