### ISSUE TITLE
Building your Brewfile

### ISSUE THREAD

**Issue by MikeiLL** [jacobwgillespie/dotfiles#7]
Hey man.

Looks like a great, insightful fork. Can you make a recommendation on how to build my Brewfile from current settings?

`brew list` outputs just a few casks and a whole ton of formulae.

Thanks and I hope you don't mind the spam.

Mike

**Comment by jacobwgillespie** [comment]
Hey! If you'd like to create a Brewfile from scratch, there's a `brew bundle dump` command that will create a new Brewfile in the current directory with all your installed formulae and casks. That would be a good starting point I think.

After starting out, I update the Brewfile in this repo by hand, but there's a couple other useful commands:

* `brew bundle` will install everything in the Brewfile, useful for setting a new machine up from scratch
* `brew bundle cleanup` will list out formulae that aren't listed in the Brewfile and would be removed (but doesn't actually remove them)
* `brew bundle cleanup -f` actually removes extra packages that aren't listed

So for my workflow, I can install things with `brew` directly, and periodically I'll run `brew bundle cleanup` to see what extra things are installed. I'll then add anything I want to keep to the Brewfile, and finally run `brew bundle cleanup -f` to remove anything I don't want to keep.

There's some other commands you can find at `brew bundle --help` too.

**Comment by MikeiLL** [comment]
Super helpful, man. Sending a tiny PR with addition to the README, if it's useful.

**Comment by jacobwgillespie** [comment]
Perfect, thanks for the PR 🎉
