### ISSUE TITLE
Git Aliases

### ISSUE THREAD

**Issue by MikeiLL** [jacobwgillespie/dotfiles#9]
Loving this, so far!

When I run `git commit <some file>` now, it prompts me for either the `-F` (file) and/or `-m` (message) flag.

However I prefer to write my commit messages in vim, my git editor.

I have looked around in `bin`, `config` and `symlinks/.gitconfig.symlink` and am still at a loss.

Can you help?

**Comment by jacobwgillespie** [comment]
Not sure what it could be in your particular case, but you might check the `core.editor` config setting in `symlinks/.gitconfig.symlink` - that's the setting that controls what editor git opens for things like commit messages, I'd assume you could set it to `vim`.

```gitconfig
[core]
	editor = e -w
```

In this repo, it's set to `e -w`, which runs `bin/e`, which in turn opens VS Code via the `code` CLI. The `-w` means "wait" as by default the `code` CLI will immediately exit after opening the file, which isn't what git needs.

**Comment by MikeiLL** [comment]
Exactly!

```gitconfig
[core]
 	editor = vim
```

Did the trick. Thank you again.
